package com.zapgo.tests;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.time.Duration;
import java.util.List;

/**
 * MapPageTest — tests for the Map/route-planning page (/app).
 *
 * Selectors derived from src/pages/MapPage.jsx:
 *
 *   Leaflet map container → div.leaflet-container  (auto-generated by Leaflet)
 *   Map div (id)          → div#map
 *
 *   Start input           → input.field-input[placeholder='e.g. Srinagar']
 *   Destination input     → input.field-input[placeholder='e.g. Kanyakumari']
 *   Initial Charge input  → input.field-input[placeholder='Initial %']
 *   Final Charge input    → input.field-input[placeholder='Final %']
 *   Range input           → input.field-input[placeholder='between 1 and 2000']
 *   Hours input           → input.field-input[placeholder='HH']
 *   Minutes input         → input.field-input[placeholder='MM']
 *
 *   Plan Route button     → button.plan-btn
 *   Route details section → div#routeDetails  (hidden until route found)
 *   Trip Summary          → div.trip-summary  (inside #routeDetails)
 *   Confirm Booking btn   → button.book-btn   (inside #routeDetails)
 *
 * @BeforeClass performs login then navigates to /app.
 */
public class MapPageTest extends BaseTest {

    private static final String EMAIL    = "testuser@zapgo.com";
    private static final String PASSWORD = "Test@1234";

    private static final Duration WAIT      = Duration.ofSeconds(15);
    private static final Duration LONG_WAIT = Duration.ofSeconds(60); // route calculation can be slow

    // -----------------------------------------------------------------------
    // @BeforeClass – log in and open the map page
    // -----------------------------------------------------------------------

    @BeforeClass
    public void loginAndOpenMapPage() {
        navigateTo("/login");
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // Email / password login
        WebElement emailInput = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.cssSelector("input[placeholder='Email Address']"))
        );
        emailInput.clear();
        emailInput.sendKeys(EMAIL);

        driver.findElement(By.cssSelector("input[placeholder='Password']")).sendKeys(PASSWORD);
        driver.findElement(By.cssSelector("button.primary-btn")).click();

        // Wait for app page
        wait.until(ExpectedConditions.urlContains("/app"));
        navigateTo("/app");
    }

    // -----------------------------------------------------------------------
    // Tests
    // -----------------------------------------------------------------------

    /**
     * Test 1: Leaflet map container is present and visible on the page.
     * Leaflet renders a <div class="leaflet-container"> inside the host div#map.
     */
    @Test(priority = 1)
    public void testMapLoads() {
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // The host div with id="map" must exist (MapPage.jsx line 594: <div ref={mapRef} id="map" />)
        WebElement mapDiv = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.id("map"))
        );
        Assert.assertNotNull(mapDiv, "Map host div#map should exist in the DOM");

        // Leaflet adds .leaflet-container once it initialises
        WebElement leafletContainer = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.leaflet-container"))
        );
        Assert.assertTrue(leafletContainer.isDisplayed(),
                "Leaflet map container should be visible on the page");
    }

    /**
     * Test 2: The route planning form inputs are visible.
     * MapPage.jsx uses class="field-input" for all sidebar inputs.
     * We locate each by its unique placeholder text.
     */
    @Test(priority = 2)
    public void testRouteFormIsVisible() {
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // Start location input (placeholder="e.g. Srinagar")
        WebElement startInput = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.cssSelector("input.field-input[placeholder='e.g. Srinagar']"))
        );
        Assert.assertTrue(startInput.isDisplayed(), "Start input should be visible");

        // Destination input (placeholder="e.g. Kanyakumari")
        WebElement destInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='e.g. Kanyakumari']"));
        Assert.assertTrue(destInput.isDisplayed(), "Destination input should be visible");

        // Initial charge (placeholder="Initial %")
        WebElement initCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Initial %']"));
        Assert.assertTrue(initCharge.isDisplayed(), "Initial Charge input should be visible");

        // Final charge (placeholder="Final %")
        WebElement finalCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Final %']"));
        Assert.assertTrue(finalCharge.isDisplayed(), "Final Charge input should be visible");

        // Range (placeholder="between 1 and 2000")
        WebElement rangeInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='between 1 and 2000']"));
        Assert.assertTrue(rangeInput.isDisplayed(), "Range input should be visible");
    }

    /**
     * Test 3: Fill the route form with Mumbai → Pune and click Plan Route.
     * Wait for the route details section (div#routeDetails) to appear, which
     * proves the route was found and the trip summary rendered.
     *
     * Journey time inputs (HH / MM) are required by the form validation.
     */
    @Test(priority = 3)
    public void testRouteCalculation() {
        navigateTo("/app");
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // Start
        WebElement startInput = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.cssSelector("input.field-input[placeholder='e.g. Srinagar']"))
        );
        startInput.clear();
        startInput.sendKeys("Mumbai");

        // Destination
        WebElement destInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='e.g. Kanyakumari']"));
        destInput.clear();
        destInput.sendKeys("Pune");

        // Initial charge
        WebElement initCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Initial %']"));
        initCharge.clear();
        initCharge.sendKeys("80");

        // Final charge
        WebElement finalCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Final %']"));
        finalCharge.clear();
        finalCharge.sendKeys("20");

        // Range
        WebElement rangeInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='between 1 and 2000']"));
        rangeInput.clear();
        rangeInput.sendKeys("300");

        // Journey start time: HH
        WebElement hhInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='HH']"));
        hhInput.clear();
        hhInput.sendKeys("10");

        // Journey start time: MM
        WebElement mmInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='MM']"));
        mmInput.clear();
        mmInput.sendKeys("00");

        // Click Plan Route
        driver.findElement(By.cssSelector("button.plan-btn")).click();

        // Wait up to 60 s for the route details section to appear
        // MapPage.jsx line 526: <div id="routeDetails" className="route-details">
        WebElement routeDetails = new WebDriverWait(driver, LONG_WAIT).until(
                ExpectedConditions.visibilityOfElementLocated(By.id("routeDetails"))
        );
        Assert.assertTrue(routeDetails.isDisplayed(),
                "Route details section should be visible after route calculation");

        // Trip summary must contain distance text
        WebElement tripSummary = driver.findElement(By.cssSelector("div.trip-summary"));
        Assert.assertTrue(tripSummary.isDisplayed(), "Trip summary should be visible");
        Assert.assertTrue(tripSummary.getText().contains("Distance"),
                "Trip summary should display distance information");
    }

    /**
     * Test 4: After a route is calculated the "Confirm Booking" button is visible.
     * MapPage.jsx line 559-565: <button className="book-btn">Confirm Booking</button>
     */
    @Test(priority = 4, dependsOnMethods = "testRouteCalculation")
    public void testBookingButtonAppears() {
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // The book-btn is inside routeDetails which is already visible from the previous test
        WebElement bookBtn = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("button.book-btn"))
        );
        Assert.assertTrue(bookBtn.isDisplayed(),
                "Confirm Booking button should be visible after route calculation");
        Assert.assertEquals(bookBtn.getText().trim(), "Confirm Booking",
                "Button text should be 'Confirm Booking'");
    }
}
