package com.zapgo.tests;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.time.Duration;
import java.util.List;

/**
 * MapPageTest — tests for the Map/route-planning page (/app).
 *
 * Selectors derived from src/pages/MapPage.jsx:
 *
 *   Leaflet map container → div.leaflet-container  (auto-generated by Leaflet)
 *   Map div (id)          → div#map
 *
 *   Start input           → input.field-input[placeholder='e.g. Srinagar']
 *   Destination input     → input.field-input[placeholder='e.g. Kanyakumari']
 *   Initial Charge input  → input.field-input[placeholder='Initial %']
 *   Final Charge input    → input.field-input[placeholder='Final %']
 *   Range input           → input.field-input[placeholder='between 1 and 2000']
 *   Hours input           → input.field-input[placeholder='HH']
 *   Minutes input         → input.field-input[placeholder='MM']
 *
 *   Plan Route button     → button.plan-btn
 *   Route details section → div#routeDetails  (hidden until route found)
 *   Trip Summary          → div.trip-summary  (inside #routeDetails)
 *   Confirm Booking btn   → button.book-btn   (inside #routeDetails)
 *
 * @BeforeClass performs login then navigates to /app.
 */
public class MapPageTest extends BaseTest {

    private static final String EMAIL    = "testuser@zapgo.com";
    private static final String PASSWORD = "Test@1234";

    private static final Duration WAIT      = Duration.ofSeconds(15);
    private static final Duration LONG_WAIT = Duration.ofSeconds(60); // route calculation can be slow

    // -----------------------------------------------------------------------
    // @BeforeClass – log in and open the map page
    // -----------------------------------------------------------------------

    @BeforeClass
    public void loginAndOpenMapPage() {
        navigateTo("/login");
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // Email / password login
        WebElement emailInput = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.cssSelector("input[placeholder='Email Address']"))
        );
        emailInput.clear();
        emailInput.sendKeys(EMAIL);

        driver.findElement(By.cssSelector("input[placeholder='Password']")).sendKeys(PASSWORD);
        driver.findElement(By.cssSelector("button.primary-btn")).click();

        // Wait for app page
        wait.until(ExpectedConditions.urlContains("/app"));
        navigateTo("/app");
    }

    // -----------------------------------------------------------------------
    // Tests
    // -----------------------------------------------------------------------

    /**
     * Test 1: Leaflet map container is present and visible on the page.
     * Leaflet renders a <div class="leaflet-container"> inside the host div#map.
     */
    @Test(priority = 1)
    public void testMapLoads() {
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // The host div with id="map" must exist (MapPage.jsx line 594: <div ref={mapRef} id="map" />)
        WebElement mapDiv = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.id("map"))
        );
        Assert.assertNotNull(mapDiv, "Map host div#map should exist in the DOM");

        // Leaflet adds .leaflet-container once it initialises
        WebElement leafletContainer = wait.until(
                ExpectedConditions.presenceOfElementLocated(By.cssSelector("div.leaflet-container"))
        );
        Assert.assertTrue(leafletContainer.isDisplayed(),
                "Leaflet map container should be visible on the page");
    }

    /**
     * Test 2: The route planning form inputs are visible.
     * MapPage.jsx uses class="field-input" for all sidebar inputs.
     * We locate each by its unique placeholder text.
     */
    @Test(priority = 2)
    public void testRouteFormIsVisible() {
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // Start location input (placeholder="e.g. Srinagar")
        WebElement startInput = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.cssSelector("input.field-input[placeholder='e.g. Srinagar']"))
        );
        Assert.assertTrue(startInput.isDisplayed(), "Start input should be visible");

        // Destination input (placeholder="e.g. Kanyakumari")
        WebElement destInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='e.g. Kanyakumari']"));
        Assert.assertTrue(destInput.isDisplayed(), "Destination input should be visible");

        // Initial charge (placeholder="Initial %")
        WebElement initCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Initial %']"));
        Assert.assertTrue(initCharge.isDisplayed(), "Initial Charge input should be visible");

        // Final charge (placeholder="Final %")
        WebElement finalCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Final %']"));
        Assert.assertTrue(finalCharge.isDisplayed(), "Final Charge input should be visible");

        // Range (placeholder="between 1 and 2000")
        WebElement rangeInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='between 1 and 2000']"));
        Assert.assertTrue(rangeInput.isDisplayed(), "Range input should be visible");
    }

    /**
     * Test 3: Fill the route form with Mumbai → Pune and click Plan Route.
     * Wait for the route details section (div#routeDetails) to appear, which
     * proves the route was found and the trip summary rendered.
     *
     * Journey time inputs (HH / MM) are required by the form validation.
     */
    @Test(priority = 3)
    public void testRouteCalculation() {
        navigateTo("/app");
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // Start
        WebElement startInput = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.cssSelector("input.field-input[placeholder='e.g. Srinagar']"))
        );
        startInput.clear();
        startInput.sendKeys("Mumbai");

        // Destination
        WebElement destInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='e.g. Kanyakumari']"));
        destInput.clear();
        destInput.sendKeys("Pune");

        // Initial charge
        WebElement initCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Initial %']"));
        initCharge.clear();
        initCharge.sendKeys("80");

        // Final charge
        WebElement finalCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Final %']"));
        finalCharge.clear();
        finalCharge.sendKeys("20");

        // Range
        WebElement rangeInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='between 1 and 2000']"));
        rangeInput.clear();
        rangeInput.sendKeys("300");

        // Journey start time: HH
        WebElement hhInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='HH']"));
        hhInput.clear();
        hhInput.sendKeys("10");

        // Journey start time: MM
        WebElement mmInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='MM']"));
        mmInput.clear();
        mmInput.sendKeys("00");

        // Click Plan Route
        driver.findElement(By.cssSelector("button.plan-btn")).click();

        // Wait up to 60 s for the route details section to appear
        // MapPage.jsx line 526: <div id="routeDetails" className="route-details">
        WebElement routeDetails = new WebDriverWait(driver, LONG_WAIT).until(
                ExpectedConditions.visibilityOfElementLocated(By.id("routeDetails"))
        );
        Assert.assertTrue(routeDetails.isDisplayed(),
                "Route details section should be visible after route calculation");

        // Trip summary must contain distance text
        WebElement tripSummary = driver.findElement(By.cssSelector("div.trip-summary"));
        Assert.assertTrue(tripSummary.isDisplayed(), "Trip summary should be visible");
        Assert.assertTrue(tripSummary.getText().contains("Distance"),
                "Trip summary should display distance information");
    }

    /**
     * Test 4: After a route is calculated the "Confirm Booking" button is visible.
     * MapPage.jsx line 559-565: <button className="book-btn">Confirm Booking</button>
     */
    @Test(priority = 4, dependsOnMethods = "testRouteCalculation")
    public void testBookingButtonAppears() {
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // The book-btn is inside routeDetails which is already visible from the previous test
        WebElement bookBtn = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("button.book-btn"))
        );
        Assert.assertTrue(bookBtn.isDisplayed(),
                "Confirm Booking button should be visible after route calculation");
        Assert.assertEquals(bookBtn.getText().trim(), "Confirm Booking",
                "Button text should be 'Confirm Booking'");
    }

    // -----------------------------------------------------------------------
    // AI Route Narrator Tests (priorities 5–8)
    // Selectors derived directly from src/pages/MapPage.jsx and src/user.css:
    //
    //   Narrate button        → button.narrate-btn
    //   Loading indicator     → div.narrate-loading
    //   Response box          → div.narrate-box
    //   AI badge (in box)     → div.narrate-ai-badge   (text: "🤖 AI Generated")
    //   Spots container       → div.narrate-spots
    //   Spots title           → p.narrate-spots__title
    //   Spot cards            → div.narrate-spot-card
    //   Spot name (in card)   → span.narrate-spot-name
    // -----------------------------------------------------------------------

    /**
     * Test 5: After the Mumbai → Pune route is calculated (priority 3), the
     * "AI Route Narrator" button (button.narrate-btn) must be present, visible,
     * and not disabled.
     *
     * MapPage.jsx: disabled={narrating || totalDist === null}
     * The button only renders inside {totalDist != null && ...} so its presence
     * already implies a route exists; we additionally assert it is enabled.
     */
    @Test(priority = 5, dependsOnMethods = {"testRouteCalculation"})
    public void testNarrateButtonAppearsAfterRoute() {
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // button.narrate-btn is inside div#routeDetails, rendered after route calculation
        WebElement narrateBtn = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("button.narrate-btn"))
        );

        Assert.assertTrue(narrateBtn.isDisplayed(),
                "Narrate button (button.narrate-btn) should be visible after route calculation");

        // Must not carry the disabled attribute — totalDist is set, narrating is false
        Assert.assertFalse(
                narrateBtn.getAttribute("disabled") != null,
                "Narrate button should be enabled after a route is calculated"
        );
    }

    /**
     * Test 6: Clicking "AI Route Narrator" triggers Ollama and produces a response.
     *
     * // NOTE: Ollama must be running at http://localhost:11434 with llama3.2 before running this test
     *
     * We wait up to 90 seconds for div.narrate-box because llama3.2 runs locally
     * and the first cold-start inference (loading into GPU VRAM) can be slow.
     * Once visible we assert content length and the AI badge text.
     */
    @Test(priority = 6, dependsOnMethods = {"testNarrateButtonAppearsAfterRoute"})
    public void testNarrateRouteGeneratesOutput() {
        WebDriverWait wait       = new WebDriverWait(driver, WAIT);
        WebDriverWait ollamaWait = new WebDriverWait(driver, Duration.ofSeconds(90));

        // Click the narrate button
        WebElement narrateBtn = wait.until(
                ExpectedConditions.elementToBeClickable(By.cssSelector("button.narrate-btn"))
        );
        narrateBtn.click();

        // Wait up to 90 s for div.narrate-box to appear (Ollama inference time)
        WebElement narrateBox = ollamaWait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div.narrate-box"))
        );

        // narrate-box must be displayed
        Assert.assertTrue(narrateBox.isDisplayed(),
                "div.narrate-box should be visible after narration completes");

        // Text content must not be empty
        String boxText = narrateBox.getText().trim();
        Assert.assertFalse(boxText.isEmpty(),
                "narrate-box text content should not be empty");

        // Must be a real narration — more than 50 characters
        Assert.assertTrue(boxText.length() > 50,
                "narrate-box should contain more than 50 characters of narration text");

        // Badge (div.narrate-ai-badge) inside the box must say "AI GENERATED"
        WebElement badge = narrateBox.findElement(By.cssSelector("div.narrate-ai-badge"));
        Assert.assertTrue(badge.getText().toUpperCase().contains("AI GENERATED"),
                "div.narrate-ai-badge should contain 'AI GENERATED' text");
    }

    /**
     * Test 7: After narration, div.narrate-spots is rendered with a heading and
     * exactly 3 spot cards, each having a non-empty name.
     *
     * Reuses the narration state from priority 6 — does NOT click narrate again.
     */
    @Test(priority = 7, dependsOnMethods = {"testNarrateRouteGeneratesOutput"})
    public void testSpotsSection() {
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // Spots container must be visible
        WebElement spotsSection = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div.narrate-spots"))
        );
        Assert.assertTrue(spotsSection.isDisplayed(),
                "div.narrate-spots should be visible after narration completes");

        // Title (p.narrate-spots__title) must contain "TOP SPOTS TO VISIT"
        WebElement spotsTitle = spotsSection.findElement(By.cssSelector("p.narrate-spots__title"));
        Assert.assertTrue(spotsTitle.getText().toUpperCase().contains("TOP SPOTS TO VISIT"),
                "p.narrate-spots__title should contain 'TOP SPOTS TO VISIT'");

        // Exactly 3 spot cards must be rendered
        List<WebElement> spotCards = spotsSection.findElements(By.cssSelector("div.narrate-spot-card"));
        Assert.assertEquals(spotCards.size(), 3,
                "Exactly 3 div.narrate-spot-card elements should be rendered");

        // Each card must have a non-empty span.narrate-spot-name
        for (int i = 0; i < spotCards.size(); i++) {
            WebElement spotName = spotCards.get(i).findElement(By.cssSelector("span.narrate-spot-name"));
            String nameText = spotName.getText().trim();
            Assert.assertFalse(nameText.isEmpty(),
                    "Spot card " + (i + 1) + ": span.narrate-spot-name should not be empty");
        }
    }

    /**
     * Test 8: Without a calculated route the narrate button must be either absent
     * from the DOM or present but disabled.
     *
     * Navigates to /app fresh so totalDist resets to null. MapPage.jsx only renders
     * the narrate button inside {totalDist != null && ...}, so it will not be in the DOM.
     * After the assertion the Mumbai → Pune route is recalculated to restore page state.
     */
    @Test(priority = 8)
    public void testNarrateButtonRequiresRoute() {
        // Fresh navigation — totalDist becomes null, routeDetails block is not rendered
        navigateTo("/app");
        WebDriverWait wait = new WebDriverWait(driver, WAIT);

        // Wait for the form to be ready (plan-btn must be present)
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("button.plan-btn")));

        // Narrate button should be absent OR disabled
        List<WebElement> narrateBtns = driver.findElements(By.cssSelector("button.narrate-btn"));
        if (narrateBtns.isEmpty()) {
            // Expected: button not rendered at all because totalDist == null
            Assert.assertTrue(true,
                    "Narrate button correctly absent from DOM before route calculation");
        } else {
            // Defensive case: button is present but must carry the disabled attribute
            Assert.assertNotNull(narrateBtns.get(0).getAttribute("disabled"),
                    "Narrate button must be disabled when no route has been calculated");
        }

        // --- Restore state: recalculate Mumbai → Pune so later tests can depend on it ---
        WebElement startInput = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.cssSelector("input.field-input[placeholder='e.g. Srinagar']"))
        );
        startInput.clear();
        startInput.sendKeys("Mumbai");

        driver.findElement(By.cssSelector("input.field-input[placeholder='e.g. Kanyakumari']"))
              .sendKeys("Pune");

        WebElement initCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Initial %']"));
        initCharge.clear();
        initCharge.sendKeys("80");

        WebElement finalCharge = driver.findElement(
                By.cssSelector("input.field-input[placeholder='Final %']"));
        finalCharge.clear();
        finalCharge.sendKeys("20");

        WebElement rangeInput = driver.findElement(
                By.cssSelector("input.field-input[placeholder='between 1 and 2000']"));
        rangeInput.clear();
        rangeInput.sendKeys("300");

        driver.findElement(By.cssSelector("input.field-input[placeholder='HH']")).sendKeys("10");
        driver.findElement(By.cssSelector("input.field-input[placeholder='MM']")).sendKeys("00");

        driver.findElement(By.cssSelector("button.plan-btn")).click();

        new WebDriverWait(driver, LONG_WAIT).until(
                ExpectedConditions.visibilityOfElementLocated(By.id("routeDetails"))
        );
    }
}
